### ISSUE TITLE
NoObjectExists vs. UniqueObject

### ISSUE THREAD

**Issue by pdobrigkeit** [doctrine/DoctrineModule#409] opened 2014-05-01 08:57 UTC
I have trouble getting the use-case I have to work. If I have a form which is used for insert and update I don't know which one to use. 

In case of insert the UniqueObject fails, because the context has no identifier set yet
In case of update the NoObjectExists fails, because the own object is found...

Any solutions for this?

**Comment by Bilge** [comment] 2015-05-01 09:46
This is an outstanding problem with the current suite of generally useless validators.

In general we can say the validators are designed to cover the following scenarious:

* `ObjectExists`: n > 0
* `NoObjectExists`: n == 0
* `UniqueObject`: 0 <= n <= 1

Normally the validator you want is `UniqueObject` for both insert and update actions, but as noted, it fails when an identifier is not set. This issue is described in #380 but sadly that issue has been closed prematurely.

**Comment by TomHAnderson** [comment] 2017-11-12 00:32
@Bilge anything to add to this?  I'm inclined to just close it and if it comes up again start anew with diagnosing the way these are used (for example I think you're incorrect that UniqueObject should be used for insert and update)

**Comment by Bilge** [comment] 2017-11-12 00:37
I don't know what you're expecting from me but just closing the issue isn't going to solve anything. If you really want to do a good job you should have a clear idea of exactly what use-cases exist and exactly which validators solve them and then make sure it's clearly documented so there's no more confusion about which we should be using and in what scenarios.

**Comment by TomHAnderson** [comment] 2017-11-12 01:12
@Bilge would you consider this a documentation issue then?

**Comment by Bilge** [comment] 2017-11-12 01:14
That depends whether you can satisfy all use-cases with currently available solutions. It may be the case that once you lay it all out, you realize something is missing.

**Comment by TomHAnderson** [comment] 2017-11-13 02:47
I refactored the documentation.  If you don't see your issue covered in the new docs, @Bilge will you put up a PR to address your concerns?

https://github.com/doctrine/DoctrineModule/blob/master/docs/validator.md

**Closed by TomHAnderson** 2017-11-13 02:47 UTC
