### ISSUE TITLE
Validate-schema problem with indexes names

### ISSUE THREAD

**Issue by cbichis** [doctrine/DoctrineModule#464] opened 2015-01-04 15:56 UTC
Hello,

I am using dev-master version,

The validate-schema keeps reporting:
[Database] FAIL - The database schema is not in sync with the current mapping file.

And the orm:schema-tool:update --dump-sql

is requesting me to add an index with an obfuscated name:  CREATE INDEX IDX_D7943D682D5B0234 ON area (city);

But I already have a proper index with the name: city.

If I change the index name to IDX_D7943D682D5B0234 the schema tool is asking me to have a index city: CREATE INDEX city ON area (city);

So to be all green I am forced to add two indexes for the same field, one with the name =  field name and the other one with the name as the schema tool is suggesting me. This is happening for all my fields involved in FK relations.

**Comment by Ocramius** [comment] 2015-01-05 01:09
This is actually a duplicate of doctrine/dbal#764

Refs:

 - http://www.doctrine-project.org/jira/browse/DBAL-1063
 - http://www.doctrine-project.org/jira/browse/DBAL-1074
 - http://www.doctrine-project.org/jira/browse/DBAL-1102
 - doctrine/dbal#764
 - doctrine/dbal#743
 - https://travis-ci.org/doctrine/doctrine2/jobs/45886308#L298

Closing as duplicate. Also, this is an ORM bug that needs a fix (will happen in the next days).

**Closed by Ocramius** 2015-01-05 01:09 UTC
