### ISSUE TITLE
Deprecated: "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5

### ISSUE THREAD

**Issue by seyfer** [doctrine/DoctrineModule#511] opened 2015-06-01 09:30 UTC
```
and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.
```

```
   0.0955    7256640  36. DoctrineORMModule\Module->initializeConsole() /var/www/site.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:444
    0.1523   15584520  37. Symfony\Component\Console\Helper\DialogHelper->__construct() /var/www/site.com/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php:144

```

**Comment by Ocramius** [comment] 2015-06-01 09:31
Marking as dupe of doctrine/DoctrineORMModule#416

**Closed by Ocramius** 2015-06-01 09:31 UTC
Labels: bug
